public with sharing class passBysObj {


        public static void returnUpdateAcc(list<Account> accList) {

        for(Integer i=0 ; i < listint.size(); i++){

                accList[i].Name = 'Acc updated in class';

    }

}

 public static void returnUpdateAccWithSOQL(list<Account> accList) {

        for(Account a : i < listint.size(); i++){

                accList[i].Name = 'Acc updated in class';

    }

}
}